function req(req) require("plugins/opciones/" .. req) end
--function loada(loada) vim.g(loada) end

require("plugins/init")
require("mapeado/mapeado")
require("opciones")

req("nvim-tree")
req("nvim-ts-rainbow")
req("nvim-test")
req("auto-save")
req("alpha-nvim")
req("autoclose")
req("lualine")
req("nvim-treesitter")
req("cmp")
req("mason")
req("toggle-term")

--loada("netrw")
--loada("netrwPlugin")
--loada("netrwSettings")
--loada("netrwFileHandlers")
--loada("gzip")
--loada("zip")
--loada("zipPlugin")
--loada("tar")
--loada("tarPlugin")
--loada("getscript")
--loada("getscriptPlugin")
--loada("vimball")
--loada("vimballPlugin")
--loada("2html_plugin")
--loada("logipat")
--loada("rrhelper")
--loada("spellfile_plugin")
--loada("matchit")
