require("miModule")
require("mapeado/mapeado")
require("plugins/init")
require("opciones")

-- Plugins
require("plugins/opciones/nvim-tree")
require("plugins/opciones/autoclose")
require("plugins/opciones/lualine")
require("plugins/opciones/nvim-treesitter")
require("plugins/opciones/cmp")
require("plugins/opciones/mason")
require("plugins/opciones/luasnip")
require("plugins/opciones/toggle-term")
require("plugins/opciones/nvim-ts-rainbow")
require("plugins/opciones/nvim-navic")
